namespace enums;

public enum EventType : short
{
	EVENT_ALL = 0,
	EVENT_STAGE = 1,
	EVENT_DROP = 2,
	EVENT_LOGIN = 3,
	EVENT_BONUS = 4,
	EVENT_PVPSEASON = 5,
	EVENT_LABO = 6,
	EVENT_MONTHLY_ACTIVITY = 7,
	EVENT_ROULETTE = 8,
	EVENT_MISSION = 9,
	EVENT_TOWER = 10,
	EVENT_BOSSRUSH = 11,
	EVENT_TIME_ATTACK = 12,
	EVENT_RAID_BOSS = 13,
	EVENT_CRUSADE = 15,
	EVENT_RESEARCH = 16,
	EVENT_TOTALWAR = 17
}
