namespace StageLib;

public enum STAGE_SYNC_OBJ_MODE
{
	STAGE_SYNC_OBJ_PLAYER,
	STAGE_SYNC_OBJ_USETIME,
	STAGE_SYNC_OBJ_MEMBERINFO,
	STAGE_SYNC_OBJ_SEASONDATA,
	STAGE_SYNC_OBJ_PAUSE,
	STAGE_SYNC_OBJ_ENEMY_DATA,
	STAGE_SYNC_OBJ_GAMESAVEDATA
}
