namespace StageLib;

public enum STAGE_STATUS
{
	NONE,
	STAGE_BUFF,
	STAGE_SHOT_BULLET,
	STAGE_SOB_ADDMEASURE,
	STAGE_SOB_ADDPET,
	STAGE_DEL_BUFF,
	STAGE_DEL_MARKED_BUFF,
	STAGE_ADD_GAMESAVEDATA,
	STAGE_CHECK_OUTDEAD,
	STAGE_RESET_OUTDEAD,
	STAGE_PLAYSOUND,
	STAGE_PLAYFX,
	STAGE_UPDATE_PASSIVESKILL
}
