namespace StageLib;

public enum STAGE_QUEST_TYPE
{
	QUEST_NONE,
	QUEST_KILLENEMY_CALLEVENT,
	QUEST_EVENTID_COUNT,
	QUEST_CHECK_BUFF,
	QUEST_CHECK_OBJALIVE,
	QUEST_CAMPAIGN_SCORE,
	QUEST_MKILLENEMY_CALLEVENT
}
