namespace StageLib;

public enum STAGE_EVENT
{
	NONE,
	STAGE_VOICE_ON,
	STAGE_ENEMYEVENT_STOP,
	STAGE_PLAYER_REBORN,
	STAGE_SYNC_COUNTDOWN,
	STAGE_SYNC_SCORE,
	STAGE_SYNC_RECONNECTEVENT,
	STAGE_SYNC_OBJ,
	STAGE_SYNC_PVPUI,
	STAGE_PLAYER_CHANGECHARACTER,
	STAGE_SYNC_BATTLETIMER,
	STAGE_SET_RECONNECT,
	STAGE_SYNC_FLAG_SCORE,
	STAGE_SYNC_STAGEFALL,
	STAGE_SYNC_PVPENDDATA,
	STAGE_SYNC_WAITSTAGECTRL,
	STAGE_SYNC_PLAYERGIVEUP,
	STAGE_SYNC_PLAYERSPAWN,
	STAGE_SYNC_PLAYEROUTGAME,
	STAGE_SYNC_DMGERROR_ENDGAME,
	STAGE_SYNC_BATTLEEND_RQ,
	STAGE_START_SUMMON_ENEMY,
	STAGE_ADD_COUNTDOWN,
	STAGE_SYNC_MAX
}
